version: 0.2
phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y nodejs npm
      - sudo apt-get install -y nginx
      - echo Installing Node.js
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo Configuring Nginx
      - echo Build completed on `date`
artifacts:
  files:
    - /var/www/html/index.html
    - /var/www/html/*
  discard-paths: yes
  base-directory: /var/www/html
  name: ReFeast-Web-App
  location: /var/www/html