version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23.10.0
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - ls -al
      - mkdir -p output
      - cp public/index.html output/

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: yes
  name: ReFeast-Web-App